apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:R/Q7HKTp28mg00hR+pXb/j5iOr435ngWiG3sKNnET3SUNS2MomA3kg==,iv:+ZbNLDUKJSoYpj68NZa2Z276wgJ+2C7teBJ3jq3RV/w=,tag:ADhEW1I/SZCH6E6aI1qoLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16dzmpp89ru6w4ptwanf7ydc65236sawn6r5jwqa4g5vu68rkgy7q4le0lt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bzBIcXdTSTZQU3BXTUtN
            STZwVVN2UzlPVEU5bUd4VHkveWNMVlMvNVI4Ck1HK3VxSHo0ay8wZDU1R09XOExP
            WlUrTEp3a0IzS3FIWWlvN0FSMVMxaTgKLS0tIFJOampLQWlNZ1RYMlFYRHA5bVpB
            S0thNkFCWTdEWUNtdGQzM3Q0U1poZmMKfCFc4U5edh3kvtM8rlpVG5yOOqVNVA1L
            J0xxkmNKO7VYJaOF4rF3ZC0vNrd6wMxJZ3RmKjBENiUsaMl5pGomhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T21:15:34Z"
    mac: ENC[AES256_GCM,data:h7QgwOo6Gh4zpmtzrnvPSgAb06PWD9c+W1A43141kUJQT+lyzSBQf9hkGAyg06wIwlN4PDeTwNXRF4jgWDvqaCEP92eF/obeaGdjCJxx+9oZpzniTjNyPjYO1hS0UnZqdTDLqOVaHNJcmiz8EIHRGfp5zOpXfZUcCW7GHzV1Ub0=,iv:XlB8c6H0v1LoBPubpUURwYHlNBPjRlJvJewr+ejYsUI=,tag:4M5LhSviD8CLXIeOcRU33Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
